spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    password: root
    username: root
  jpa:
    show-sql: true
    generate-ddl: true
  application:
    name: product_service